all: pdns-dulaunoy-kaplan-passive-dns-cof

pdns-dulaunoy-kaplan-passive-dns-cof: 	pdns-dulaunoy-kaplan-passive-dns-cof.tex
	pdflatex pdns-dulaunoy-kaplan-passive-dns-cof.tex

clean:
	rm -f pdns-dulaunoy-kaplan-passive-dns-cof.log pdns-dulaunoy-kaplan-passive-dns-cof.out \
		pdns-dulaunoy-kaplan-passive-dns-cof.vrb pdns-dulaunoy-kaplan-passive-dns-cof.toc \
		pdns-dulaunoy-kaplan-passive-dns-cof.snm pdns-dulaunoy-kaplan-passive-dns-cof.pdf \
		pdns-dulaunoy-kaplan-passive-dns-cof.nav pdns-dulaunoy-kaplan-passive-dns-cof.aux \
		content.aux content.log \
		pdns-dulaunoy-kaplan-passive-dns-cof.pdf
